### PR TITLE
Fix DEPRECATED Action signature

### PR DESCRIPTION
**Pull request by abrandemuehl**
Just a change in function signature for a library.

### CODE REVIEW

**Comment by agocs** [comment]
YTMND

**Comment by agocs** [comment]
Oh, shoot, I can't merge this any more. @cstroe ?

**Comment by cstroe** [comment]
@agocs How do we go about solving this?  I'm not sure I want to become the maintainer of this project (love the project, but I have other things on my plate), and I can't add you as a collaborator without our security person saying something.

**Comment by agocs** [comment]
I guess I could fork it and ~~ignore issues~~ act as the maintainer, and you could update the BS/RMQST README.md to say "Hey, go look at agocs/RMQST for the real repository".

**Pull request merged**
